version: "3"

services:
  zeppelin:
    image: apache/zeppelin:0.11.0
    container_name: zeppelin
    platform: linux/amd64
    restart: always
    ports:
      - 8089:8080
    volumes:
      - ./data:/opt/data
      - ./resources:/opt/resources
      - ./notebooks:/zeppelin/notebook
    environment:
      - ZEPPELIN_LOG_DIR=/zeppelin/logs
      - ZEPPELIN_NOTEBOOK_DIR=/zeppelin/notebook